### ISSUE TITLE
[Bug]: [CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

### ISSUE THREAD

**Issue by haidernaqvi87** [Baseflow/flutter-geolocator#1293]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Just trying to run my function getCurrentLocation

### Expected results

should get the current position or else throw an error

### Actual results

Screen unresponsive 

### Code sample

<details><summary>Just a function to get location</summary>
  Future<Position> getCurrentLocation({@required BuildContext buildContext, @required bool serviceEnabled, @required LocationPermission permission}) async {
    try {
      serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        return Future.error('services disabled');
      }

      permission = await Geolocator.checkPermission();
      print(permission.toString());
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.whileInUse || permission == LocationPermission.always) {
            return await Geolocator.getCurrentPosition(
              desiredAccuracy: LocationAccuracy.medium,
              timeLimit: const Duration(seconds: 20),);
        }
        return Future.error('denied');
      }
      else if (permission == LocationPermission.deniedForever) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.whileInUse || permission == LocationPermission.always) {
            return await Geolocator.getCurrentPosition(
              desiredAccuracy: LocationAccuracy.medium,
              timeLimit: const Duration(seconds: 20),);
        }
        return Future.error('permanently denied');
      } else {
        return await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.medium,timeLimit: const Duration(seconds: 20),);
      }
    } catch (e) {
      hideLoading();
      return null;
    }

  }

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by alliejc** [comment]
I'm also experiencing this issue

**Comment by BenGomesAOA** [comment]
Did you find a solution for this.

**Comment by jonneroni** [comment]
I've also been experiencing this around May-June but I think they already merged a [fix](https://github.com/Baseflow/flutter-geolocator/pull/1265) for this. They just haven't updated the package in pub.dev.

**Comment by JeroenWeener** [comment]
This issue has indeed been fixed in #1265. You can pull in the latest version of the `geolocator_apple` package by running `dart pub upgrade`. If you check your `pubspec.lock` file, you should see an entry saying

```
  geolocator_apple:
    ...
    version: "2.2.7"
```

Anything above 2.2.6 should include the fix.

**Comment by Ellynnn** [comment]
@JeroenWeener my geolocator_apple is already version 2.3.2 but the problem seems to still exist...
