### ISSUE TITLE
No response when location accuracy is Medium

### ISSUE THREAD

**Issue by OsaXma** [Baseflow/flutter-geolocator#375]
## 🐛 Bug Report
 

As the title mentions, when I set the location accuracy to Medium, I don't get any response from `getCurrentPosition` and the code just stalls in there without any results or errors. I tested all the other accuracies, and it works fine. I believe this started happening after I upgraded flutter since it was not an issue before (flutter doctor output is below). 

One thing I note is that when I exit the app to the home screen and then open Google Maps, the code continues to execute right away. 

### Expected behavior
The code should return a Position when called, or return an error or a timeout.
 
### Reproduction steps
simply calling `Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.medium)`.

### Configuration

```
Flutter Doctor Output:
[✓] Flutter (Channel master, v1.13.10-pre.55, on Mac OS X 10.15.2 19C57, locale en)
    • Flutter version 1.13.10-pre.55 at /Users/osaxma/Tools/flutter
    • Framework revision bc6f270c58 (3 hours ago), 2020-01-14 13:23:03 -0800
    • Engine revision fd269f60bf
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/osaxma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```
**Version:** 
^5.2.0 
same with (^5.1.5).

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Fluxkom** [comment]
I also encountered this problem.
I think it has to do with the API 29. When I build it with 28 I can use low and medium without any issues.

**Comment by roysprojects** [comment]
I'm having the same problem while using API 29. Only LocationAccuracy.high works for me.

**Comment by Hadii1** [comment]
same happens here

**Comment by xai1983kbu** [comment]
I'm having the same problem with LocationAccuracy.medium. I am using API 28.

**Comment by tridio** [comment]
Same issue with ^5.2.1 running in API 29 when using low accuracy. Works fine with high accuracy.

**Comment by michjnich** [comment]
Can confirm it's the same with ^5.3.2+2 and API 30. Low and medium just hang and never get a response. Setting to high is the only way to get it to work.

**Comment by mvanbeusekom** [comment]
Fixed in version 6.0.0

**Comment by Infamoustrey** [comment]
On ^6.0.0 in my pubspec, with API 30 and I still receive this issue, no timeout error, the call just hangs. Changing the call to 

```dart
 Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
```

works, but any other setting in the desiredAccuracy param causes the function to hang. Verified that permissions and location service is enabled.
