### ISSUE TITLE
Android - E/location_permissions(11102): Flutter result object is null.

### ISSUE THREAD

**Issue by thoughtspeed7** [Baseflow/flutter-geolocator#424]
Using geolocator: 5.3.1. On Android 10 Emulator, "Allow-While-In-Use" permission level does not work as expected. I keep getting prompted for permissions even during the same app session. And GeolocationStatus shows as "denied" even when I've granted "Allow-While-In-Use". I also see below in my logs when I grant "Allow-While-In-Use" and access location:

E/location_permissions(11102): Flutter result object is null.

I can still read the location successfully though. But the permission prompt again and again is annoying. Code below:

```
      position = await geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.medium,
        locationPermissionLevel: GeolocationPermission.locationWhenInUse,
      );

```

**Comment by RealBug** [comment]
Hi @thoughtspeed7, I'm having the same issue on some Android emulator and iOS but didn't see why too ;( FYI, I have another response code : E/location_permissions( 4294): Flutter result object is null.

**Comment by RealBug** [comment]
A workaround that works is to put best accuracy : 
position = await Geolocator( )
            .getCurrentPosition( desiredAccuracy: LocationAccuracy.best );

**Comment by thoughtspeed7** [comment]
> A workaround that works is to put best accuracy :
> position = await Geolocator( )
> .getCurrentPosition( desiredAccuracy: LocationAccuracy.best );

@RealBug Will try this but LocationAccuracy.best takes a lot more compute time versus LocationAccuracy.medium :-(

**Comment by shanewaz-abbas** [comment]
I think I fixed this by going to my phone and setting the location to run all the time for this app. You should see the prompt the first time you run the app and using this plugin

**Comment by reyjexter** [comment]
On my end, changing to LocationAccuracy.best didn't solve the problem as it kept asking for permission. I'm using the same version which is 5.3.1.

A temporary solution was to use a different plugin to determine the current location and we'll switch back to this once this is fixed.

**Comment by mvanbeusekom** [comment]
@thoughtspeed7, @RealBug, @reyjexter this issue is now fixed in version 6.0.0-rc.4. I will hopefully being able to release the final version soon.
