### ISSUE TITLE
Doesn't return anything if GPS is turned off

### ISSUE THREAD

**Issue by praveen-gm** [Baseflow/flutter-geolocator#481]
Although there is `Geolocator().isLocationServiceEnabled()` to know if the device GPS is turned on/off and then request location. Since there is no way to turn on GPS using this plugin there needs to have a workaround to achieve the same.

`Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high) ` doesn't return null or anything if the GPS is turned off

**Comment by DhavalRKansara** [comment]
I am also facing the same issues.

**Comment by nateshmbhat** [comment]
facing same issue !

**Comment by mvanbeusekom** [comment]
@nateshmbhat which version of the geolocator plugin are you using? In our [latest release candidate](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3) we have included the feature to automatically ask the user to enable the location services when calling the `getCurrentPosition` or `getPositionStream` methods. 

Note that this will only work on Android with Google Play Services (so you should not use `forceAndroidLocationManager`). For iOS and Android using the LocationManager there are no SDKs available to automatically ask the user to enable the location services. This means you will receive a `LocationServicesDisabledException` which you can catch and alert the user that he or she should manually enable the location services (you can use the `openLocationSettings` to open the settings App, see detailed documentation [here](https://github.com/Baseflow/flutter-geolocator#settings)).

**Comment by nateshmbhat** [comment]
Its working in 6.0.0-rc but clicking on "no thanks" in the location services dialog is crashing the whole app.

```
D/AndroidRuntime(18533): Shutting down VM
E/AndroidRuntime(18533): FATAL EXCEPTION: main
E/AndroidRuntime(18533): Process: com.rakbank.falcon, PID: 18533
E/AndroidRuntime(18533): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent { (has extras) }} to activity {com.rakbank.falcon/com.nuclei.falcon.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(18533): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4976)
E/AndroidRuntime(18533): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5017)
E/AndroidRuntime(18533): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(18533): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(18533): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(18533): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
E/AndroidRuntime(18533): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(18533): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(18533): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/AndroidRuntime(18533): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18533): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(18533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(18533): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(18533): 	at com.nateshmbhat.card_scanner.CardScannerPlugin.onActivityResult(CardScannerPlugin.java:105)
E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:704)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:508)
E/AndroidRuntime(18533): 	at android.app.Activity.dispatchActivityResult(Activity.java:8140)
E/AndroidRuntime(18533): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4969)
E/AndroidRuntime(18533): 	... 11 more
```

**Comment by praveen-gm** [comment]
The issue has been fixed in the version [https://pub.dev/packages/geolocator/versions/6.0.0-rc.3](6.0.0-rc.3) and works as expected.
as @mvanbeusekom discussed above, It now asks for the user to enable location services when `getCurrentPosition()` is called and when the user denies enabling location it returns a **PlatformException**

**Comment by nateshmbhat** [comment]
@praveen-gm it is still crashing the app even in 6.0.0-rc.3  when user clicks on "no thanks"

**Comment by mvanbeusekom** [comment]
@praveen-gm thank you very much for testing and giving feedback, it is much appreciated.

@nateshmbhat did you test this with the latest (6.0.0-rc.3) version or did you use the 6.0.0-rc.1 version when you received this error?

**Comment by nateshmbhat** [comment]
I used 6.0.0-rc.3 itself.

**Comment by praveen-gm** [comment]
> Its working in 6.0.0-rc but clicking on "no thanks" in the location services dialog is crashing the whole app.
> 
> ```
> D/AndroidRuntime(18533): Shutting down VM
> E/AndroidRuntime(18533): FATAL EXCEPTION: main
> E/AndroidRuntime(18533): Process: com.bank.falcon, PID: 18533
> E/AndroidRuntime(18533): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent { (has extras) }} to activity {com.rakbank.falcon/com.nuclei.falcon.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
> E/AndroidRuntime(18533): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4976)
> E/AndroidRuntime(18533): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5017)
> E/AndroidRuntime(18533): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> E/AndroidRuntime(18533): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> E/AndroidRuntime(18533): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> E/AndroidRuntime(18533): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
> E/AndroidRuntime(18533): 	at android.os.Handler.dispatchMessage(Handler.java:107)
> E/AndroidRuntime(18533): 	at android.os.Looper.loop(Looper.java:214)
> E/AndroidRuntime(18533): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
> E/AndroidRuntime(18533): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(18533): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
> E/AndroidRuntime(18533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> E/AndroidRuntime(18533): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
> E/AndroidRuntime(18533): 	at com.nateshmbhat.card_scanner.CardScannerPlugin.onActivityResult(CardScannerPlugin.java:105)
> E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
> E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
> E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
> E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:704)
> E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:508)
> E/AndroidRuntime(18533): 	at android.app.Activity.dispatchActivityResult(Activity.java:8140)
> E/AndroidRuntime(18533): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4969)
> E/AndroidRuntime(18533): 	... 11 more
> ```

you need to use try/catch around the `getCurrentPosition`, catch for **LocationServiceDisabledException**, and handle when the user taps No Thanks

**Comment by nateshmbhat** [comment]
The following code crashes the application when user clicks on "No Thanks" 

```
try {
            var location = await getCurrentPosition(desiredAccuracy: LocationAccuracy.low);
            onLocationDetected(location);
          } catch (e) {
            getLogger().w('User denied location service !');
          }
```

**Comment by nateshmbhat** [comment]
its not supposed to crash. it's supposed to raise an exception !

**Comment by mvanbeusekom** [comment]
@nateshmbhat the problem is not with the geolocator but in the "card_scanner" plugin, as you can see in this stack trace:

```
E/AndroidRuntime(18533): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(18533): 	at com.nateshmbhat.card_scanner.CardScannerPlugin.onActivityResult(CardScannerPlugin.java:105)
E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(18533): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:704)
E/AndroidRuntime(18533): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:508)
E/AndroidRuntime(18533): 	at android.app.Activity.dispatchActivityResult(Activity.java:8140)
E/AndroidRuntime(18533): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4969)
```
The card_scanner plugin also implements the `ActivityResultListener` interface (which is perfectly fine) and thus also receives the result when the user selects the "no thanks" option. Unfortunately the card_scanner `onActivityResult` method doesn't correctly test the `requestCode` and tries to access the `FlutterResult` object which at that time is `null` and causes the crash. You can see it in the following code snippet or the card_scanner (here is a link to the code on [GitHub](https://github.com/nateshmbhat/card-scanner-flutter/blob/b393a08fdf702ae95382935689dce20b5faad92d/android/src/main/java/com/nateshmbhat/card_scanner/CardScannerPlugin.java#L104)):

``` dart
    @Override
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == SCAN_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            if (data != null && data.hasExtra(CardScannerCameraActivity.SCAN_RESULT)) {
                CardDetails cardDetails = data.getParcelableExtra(CardScannerCameraActivity.SCAN_RESULT);
                pendingResult.success(cardDetails.toMap());
            } else {
                pendingResult.success(null);
            }

            pendingResult = null;
            return true;
        } else if (resultCode == Activity.RESULT_CANCELED) {
            pendingResult.success(null); // This line is causing the crash
            pendingResult = null;
        }
        return false;
    }
```

**Comment by nateshmbhat** [comment]
Hey @mvanbeusekom thanks for the tip ! 
that was really helpful bro :D

**Comment by mvanbeusekom** [comment]
Glad I could help! I will close this issue when the final version of 6.0.0 is released (I am aiming to do so this Friday)
