### ISSUE TITLE
Lost connection to device. 

### ISSUE THREAD

**Issue by smolugu** [Baseflow/flutter-geolocator#560]
After I change location permission access in app settings, terminal in VS Code out puts "Lost connection to device".

This happens only on Android. Not sure if this is related to geolocator plugin or flutter. 
I am using geolocator 5.3.0 and Flutter 1.22.2

Any help is appreciated.

Regards,
Shyam

**Comment by mvanbeusekom** [comment]
This problem is solved in version 6 of the geolocator. Where it will output a `PermissionDeniedException` when removing permissions while listening for location updates.

**Comment by smolugu** [comment]
@mvanbeusekom Thank you! I will update the plugin.

**Comment by smolugu** [comment]
Hi @mvanbeusekom, I am still having the same issue after updating the plugin to latest version.

below is my code:

```
Geolocator.getPositionStream(
            distanceFilter: 150,
            forceAndroidLocationManager: true,
            desiredAccuracy: LocationAccuracy.high).listen((location) {
          locationData.updateCurrentLocation(location);
        }, onError: (err) {
          print('location stream error: $err');
        });
```

Thank you!
Shyam.

**Comment by smolugu** [comment]
<img width="793" alt="Screen Shot 2020-11-08 at 10 24 59 PM" src="https://user-images.githubusercontent.com/8217755/98471319-6fc67e80-2211-11eb-9c7e-87c00e62039f.png">

@mvanbeusekom hi, please have a look at this image from sentry.

Thank you!
Shyam.
