### ISSUE TITLE
Geolocator.requestPermission() never returns in Android 5.0 (API 21)

### ISSUE THREAD

**Issue by danilocubos** [Baseflow/flutter-geolocator#610]
## 🐛 Bug Report

`Geolocator.requestPermission()` never returns in Android 5.0 (API 21).

### Expected behavior
It could always return `LocationPermission.always` as Android 5.1 (API 22) and below does not require explicit location permission request.

### Reproduction steps
1. Run your app in an Android 5.0 emulator or physical device. I did not test for Android 5.1 or other versions below, but it will probably have the same behavior.

2. Run the following code:
```
final permissionStatus = await Geolocator.requestPermission();
print('This line is never reached');
```

### Configuration

**Version:**  
geolocator: ^6.1.8+1
flutter 1.22.4

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by robertoalvesneto** [comment]
hello danil, you can see my issue? I think it's a similar case, but i haven't received help yet . tkx!

**Comment by mvanbeusekom** [comment]
@danilocubos, I have just released version 6.1.9 of the [geolocator plugin](https://pub.dev/packages/geolocator) which includes the fix you provided in #611.

Thank you very much for your contribution, it is much appreciated.

@robertoalvesneto can you test if this also solves your problem? If not, please follow up in #584 and I will get back to you.

**Comment by robertoalvesneto** [comment]
@mvanbeusekom It didn't solve my problem. But my problem is the same in #585, i'm  following

**Comment by hiroki12031997** [comment]
Thank you from japan!
