### ISSUE TITLE
geolocator_apple-1.2.0 uses methods not available on macOS

### ISSUE THREAD

**Issue by michpohl** [Baseflow/flutter-geolocator#835]
Working on an app that should be deployable on Android, iOS and macOS.
Using `geolocator 7.6.1`, building for macOS fails with this error:

```
Command CompileSwift failed with a nonzero exit code
/Users/user/Library/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.0/macos/Classes/Handlers/PermissionHandler.m:52:29: error: 'requestWhenInUseAuthorization' is unavailable: not available on macOS
      [self.locationManager requestWhenInUseAuthorization];
                            ^
In module 'CoreLocation' imported from /Users/user/Library/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.0/macos/Classes/Handlers/PermissionHandler.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocationManager.h:406:1: note: 'requestWhenInUseAuthorization' has been explicitly marked unavailable here
- (void)requestWhenInUseAuthorization API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(macos);
```

Flutter, Cocoapods, Xcode are all up to date on a machine running Catalina(10.15.7). Flutter doctor reports no issues. Posting this as a question since I'm not sure if this can be an error on my side or if there's a bug in `geolocator_apple`...
any help appreciated!

**Comment by mvanbeusekom** [comment]
Hi @michpohl, 

That is a bit strange, Apple's [documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620562-requestwheninuseauthorization?language=objc) clearly mentions that this method is available on macOS 10.15+.

Also when I create a quick test application I don't run into any problems. Here are the steps I took:

1. Create a new Flutter application: `flutter create --platforms=macos issue_835`;
2. Add the correct permissions to the `macos/Runner/Info.plist` file (see example file below);
3. Add the necessary entitlements to the `macos/Runner/DebugProfile.entitlements` and `macos/Runner/Release.entitlements` files (see example files below);
4. Add the dependency to the `pubspec.yaml` file (see example file below);
5. Update the `main.dart` file to use the geolocator plugin (see example below).

After applying these changes I am able to build and run the app correctly as a macOS App. Hitting the floating action button will show the permissions dialog and afterwards print the location information to the console.

<details>
<summary>Info.plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIconFile</key>
	<string></string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSMinimumSystemVersion</key>
	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>
	<key>NSHumanReadableCopyright</key>
	<string>$(PRODUCT_COPYRIGHT)</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSLocationUsageDescription</key>
	<string>This app needs access to location.</string>
</dict>
</plist>
```
</details>

<details>
<summary>DebugProfile.entitlements</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.personal-information.location</key>
	<true/>
</dict>
</plist>
```
</details>

<details>
<summary>Release.entitlements</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.personal-information.location</key>
	<true/>
</dict>
</plist>
```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: issue_835
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

  dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.6.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Geolocator.getCurrentPosition().then((position) => print(position));

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

Here is the output of my `flutter doctor -v` command:

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/maurits/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 58.0.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 93.0.4577.82
```

Since it seems to work on my machine and the example App also compiles correctly in our CI environment (GitHub Actions), it looks to be some error on your side.

**Comment by michpohl** [comment]
Thank you @mvanbeusekom! Will replicate the example app and if that works should be able to figure out the difference in setup to my app. Will reply with results

**Comment by michpohl** [comment]
Unfortunately, the error persists. The test application won't build, aborting with the same error.
I've used your exact snippets to replace the generated ones so I'd assume it should be the same app.
Only difference I can see currently is I am still on Catalina...?

Here's my `flutter doctor -v` output:

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1417 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/michaelpohl/library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/michaelpohl/library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/michaelpohl/library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+0-b77-7246554)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iphone 8 2 (mobile)                • 34E71028-80B4-4644-A211-89A376E176F0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • Mac OS X 10.15.7 19H1417 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.82
 ```

**Comment by mvanbeusekom** [comment]
Could you check if you can update Xcode? I noticed that I am on `Xcode 12.5.1, Build version 12E507` while you are on `Xcode 12.0.1, Build version 12A7300`. 

It is possible that this would bring in an updated version of the `CoreLocation` SDK which will allow support for the particular permission. Although I am not sure if this version of Xcode is bound to the version of MacOS X (since you are still on Catalina).

This would be worth a try though.

**Comment by michpohl** [comment]
According to Xcode, the App Store and the `softwareupdate` tool I have no updates available. 12.5.1 requires Big Sur and I'm still on Catalina. I'm willing to update (I guess I have been holding off long enough now) later today to see if 12.5.1 fixes the issue. In that case it would mean though, that it is a requirement to be on Big Sur to compile a project for macOS using the current geolocator release

**Comment by mvanbeusekom** [comment]
Maybe hold on with updating as you are the perfect test subject (this is a bad way of saying you are very valuable to us ;)).

I will try to do some more research as it seems that on macOS (and MacOS X) one does not explicitly have to request permissions when accessing the device's location. Reading some threats on the internet it seems that macOS triggers the permission pop-up automatically the first time location information is retrieved.

I will make some changes and do some testing and hopefully you are also willing to help and be able to confirm the changes work correctly. This however will take a little bit of time which I hope you have available?

**Comment by michpohl** [comment]
Happy to help! I am on vacation though (without my laptop) next week, so this might slow it down a little...

**Comment by michpohl** [comment]
I am back :-) Are there any updates on this issue?

**Comment by mvanbeusekom** [comment]
Hi @michpohl, I am sorry no updates yet. Last week has been very busy, I will make sure to work on it this week and keep you in the loop.

**Comment by mvanbeusekom** [comment]
Since I felt bad not spending time on this I decided to have a look immediately and made some changes. Would you mind testing if the version in this branch work correctly?

The easiest to do this is to add a dependency override to your pubspec.yaml. Something like this:

```yaml
dependency_overrides:
  geolocator_apple:
    git:
      url: git@github.com:baseflow/flutter-geolocator.git
      path: geolocator_apple
      ref: issue/835
```

Please let me know if you run into any issues.

**Comment by michpohl** [comment]
Will try asap!

**Comment by michpohl** [comment]
One error is left:
```
/Users/user/.pub-cache/git/flutter-geolocator-26830e289fded43271cc1682ea5d21c2d28302a4/geolocator_apple/apple/Classes/Utils/LocationAccuracyMapper.m:28:24: error: use of undeclared identifier 'kCLLocationAccuracyReduced'; did you mean 'kCLLocationAccuracyBest'?
                return kCLLocationAccuracyReduced;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
                       kCLLocationAccuracyBest
In module 'CoreLocation' imported from /Users/user/.pub-cache/git/flutter-geolocator-26830e289fded43271cc1682ea5d21c2d28302a4/geolocator_apple/apple/Classes/Utils/LocationAccuracyMapper.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocation.h:113:36: note: 'kCLLocationAccuracyBest' declared here
CL_EXTERN const CLLocationAccuracy kCLLocationAccuracyBest;
```

Seems like this is just about switching methods used for mobile to ones that are present on MacOS...might be Big Sur is more forgiving and has these present...?

**Comment by mvanbeusekom** [comment]
That is a bit strange, the code on that line looks like this:

```objc
            if (@available(iOS 14.0, macOS 11.0, *)) {
                return kCLLocationAccuracyReduced;
            } else {
                return kCLLocationAccuracyThreeKilometers;
            }
```

This means `kCLLocationAccuracyReduced` should only be used on macOS 11 and higher (which also confirms with Apples [documentation](https://developer.apple.com/documentation/corelocation/kcllocationaccuracyreduced?language=objc)). 

I can of course change this to the code below, but that doesn't really feel correct.

```objc
#if TARGET_OS_OSX
            return kCLLocationAccuracyThreeKilometers;
#else
            if (@available(iOS 14.0, macOS 11.0, *)) {
                return kCLLocationAccuracyReduced;
            } else {
                return kCLLocationAccuracyThreeKilometers;
            }
#endif
```

**Comment by michpohl** [comment]
All places that break my build have this check. I am just as confused by this. I agree that your code change doesn't feel correct. Not sure what do do with this. I might as well just update to Big Sur and call it a day. It's possible I am the only one with that problem...

**Comment by mvanbeusekom** [comment]
No I don't think so, for now I will update the code as mentioned above. Would be nice if you could test this again, I have just updated the PR.

**Comment by michpohl** [comment]
This still fails. I'm afraid more places need changes (see my link above)  -> current error:
```
Command MergeSwiftModule failed with a nonzero exit code
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-00922687390290cf9fc5cff59217285ef8a4ad67/geolocator_apple/apple/Classes/Handlers/GeolocationHandler.m:58:23: error: 'allowsBackgroundLocationUpdates' is unavailable: not available on macOS
      locationManager.allowsBackgroundLocationUpdates = [GeolocationHandler shouldEnableBackgroundLocationUpdates];
                      ^
In module 'CoreLocation' imported from /Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-00922687390290cf9fc5cff59217285ef8a4ad67/geolocator_apple/apple/Classes/Handlers/GeolocationHandler.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocationManager.h:270:35: note: 'allowsBackgroundLocationUpdates' has been explicitly marked unavailable here
@property(assign, nonatomic) BOOL allowsBackgroundLocationUpdates API_AVAILABLE(ios(9.0), watchos(4.0)) API_UNAVAILABLE(tvos, macos);
                                          
```

**Comment by mvanbeusekom** [comment]
Alright that error also makes sense as the macOS platform doesn't really know the concept of running things in the background via separate background services. I also made an quick change here to only execute this code when running on iOS platform. 

Would you mind giving it another try (I have updated the PR)?

**Comment by michpohl** [comment]
Sorry, more errors :-(

```
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:32:35: error: no visible @interface for 'CLLocationManager' declares the selector 'accuracyAuthorization'
    switch ([self.locationManager accuracyAuthorization]) {
             ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:58:33: error: no visible @interface for 'CLLocationManager' declares the selector 'accuracyAuthorization'
      if ([self.locationManager accuracyAuthorization] == CLAccuracyAuthorizationFullAccuracy) {
           ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:58:59: error: use of undeclared identifier 'CLAccuracyAuthorizationFullAccuracy'
      if ([self.locationManager accuracyAuthorization] == CLAccuracyAuthorizationFullAccuracy) {
                                                          ^
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:56:27: error: no visible @interface for 'CLLocationManager' declares the selector 'requestTemporaryFullAccuracyAuthorizationWithPurposeKey:completion:'
    [self.locationManager requestTemporaryFullAccuracyAuthorizationWithPurposeKey:purposeKey
     ~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:33:12: error: use of undeclared identifier 'CLAccuracyAuthorizationFullAccuracy'
      case CLAccuracyAuthorizationFullAccuracy:
           ^
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-6a2be452d53fcbb2ceece3527f17a2467e46b92f/geolocator_apple/apple/Classes/Handlers/LocationAccuracyHandler.m:35:12: error: use of undeclared identifier 'CLAccuracyAuthorizationReducedAccuracy'
      case CLAccuracyAuthorizationReducedAccuracy:
```

**Comment by mvanbeusekom** [comment]
Alright, now it is starting to get time to rethink the solution. Let me investigate a bit more. I hope you will hang on a little bit, your test input is very valuable.

**Comment by mvanbeusekom** [comment]
@michpohl sorry for all the hassle, I just came across this [article](https://eclecticlight.co/2020/07/21/big-sur-is-both-10-16-and-11-0-its-official/) which explains that on MacOS X  10.15 and below Big Sur is reported as version 10.16 (and not 11.0). 

I made some changes in my code and check for this version instead of 11.0. I am not really sure this will provide a solution but it is worth a try. Would you mind testing again? If not I have found an alternative to test my self but it would require some installation and configuration which will probably take me a few extra hours.

**Comment by michpohl** [comment]
no problem. Will do as soon as I get to it. Thank you for putting so much time into this!

**Comment by michpohl** [comment]
The `allowBackgrouzndLocationUpdates` error is now back again:
```
/Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-ed59c2b3a1c0ebe720c509a7f841f69eaffd808d/geolocator_apple/apple/Classes/Handlers/GeolocationHandler.m:59:23: error: 'allowsBackgroundLocationUpdates' is unavailable: not available on macOS
      locationManager.allowsBackgroundLocationUpdates = [GeolocationHandler shouldEnableBackgroundLocationUpdates];
                      ^
In module 'CoreLocation' imported from /Users/user/Library/flutter/.pub-cache/git/flutter-geolocator-ed59c2b3a1c0ebe720c509a7f841f69eaffd808d/geolocator_apple/apple/Classes/Handlers/GeolocationHandler.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocationManager.h:270:35: note: 'allowsBackgroundLocationUpdates' has been explicitly marked unavailable here
@property(assign, nonatomic) BOOL allowsBackgroundLocationUpdates API_AVAILABLE(ios(9.0), watchos(4.0)) API_UNAVAILABLE(tvos, macos);
```

**Comment by mvanbeusekom** [comment]
Hi @michpohl, 

I managed to reproduce the errors also on my machine by downloading and using Xcode 12.0.1 (via the following site: https://developer.apple.com/download/all/?q=xcode).

I managed to resolve all problems that showed up on my machine (same as you indicated above) and was able to compile and run the example application. I have updated the PR and was wondering if you could give it one final try (it should now also work correctly for you, but good to make sure)?

**Comment by michpohl** [comment]
Yes, I can confirm this works! ❤️

**Comment by mvanbeusekom** [comment]
Awesome, thank you very much. I will make sure to merge and publish these fixes today.

**Comment by michpohl** [comment]
That is great! Thank you for investing so much time into this!

**Comment by mvanbeusekom** [comment]
@michpohl, just a quick update: I have just release version 1.2.1 of the `geolocator_apple` package. Please make sure you remove the dependency override and run `flutter pub upgrade` to get the latest version of the geolocator and it's dependencies and you should be good to go.
